In [1]:
import pandas as pd
import numpy as np

In [2]:
heart_disease = pd.read_csv('./041 heart-disease.csv')


In [3]:
# Consulting the map and it says to try LinearSVC
from sklearn.svm import LinearSVC
from sklearn.model_selection import train_test_split
np.random.seed(42)
X = heart_disease.drop('target', axis=1)
y = heart_disease['target']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

# Instantiate LinearSVC
model = LinearSVC()
model.fit(X_train, y_train)

model.score(X_test, y_test)

C:\ProgramData\Anaconda3\envs\tf\lib\site-packages\sklearn\svm\_base.py:985: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn("Liblinear failed to converge, increase "


0.8688524590163934

In [4]:
from sklearn.ensemble import RandomForestClassifier

np.random.seed(42)
model = RandomForestClassifier()
model.fit(X_train, y_train)

model.score(X_test, y_test)


0.8360655737704918

* have a structured data - use ensemble methods
* have an unstructured data - use deep learning or transfer learning

# 3. Fit the model/algorithm on our data and use it to make predictions
X = features, features variables, data
<p>y = labels, targets, target values

In [5]:
from sklearn.ensemble import RandomForestClassifier
np.random.seed(42)

clf = RandomForestClassifier()
clf.fit(X_train, y_train)

clf.score(X_test, y_test)

0.8360655737704918

# 3.2 Make predictions using a ML model
<p> 2 ways to make predictions:
1. 'predict()'
2. 'predict_proba()'

In [6]:
# use a trained model to make predicitons
clf.predict(np.array([1,2,6,2,4])) # this doesn't work

ValueError: Expected 2D array, got 1D array instead:
array=[1. 2. 6. 2. 4.].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [11]:
clf.predict(X_test)

array([0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0], dtype=int64)

In [12]:
np.array(y_test)

array([0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0], dtype=int64)

In [16]:
# Compare predictions to truth labesl to evaluate the model
y_preds = clf.predict(X_test)
np.mean(y_preds == y_test)

0.8360655737704918

In [17]:
clf.score(X_test, y_test)

0.8360655737704918

In [15]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_preds)

0.8360655737704918

In [19]:
# make predictions with predict_proba()
clf.predict_proba(X_test[:5])

array([[0.95, 0.05],
       [0.38, 0.62],
       [0.45, 0.55],
       [0.86, 0.14],
       [0.21, 0.79]])

In [20]:
# let's predict on the same data
clf.predict(X_test[:5])

array([0, 1, 1, 0, 1], dtype=int64)

'predict()' can also be used for regressoin models

In [24]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.datasets import load_boston
np.random.seed(42)

boston = load_boston()
boston_df = pd.DataFrame(boston['data'], columns=boston['feature_names'])
boston_df['target'] = pd.Series(boston['target'])

X = boston_df.drop('target', axis=1)
y = boston_df['target']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
model = RandomForestRegressor().fit(X_train, y_train)

y_preds = model.predict(X_test)

In [25]:
# compare the prediction to the truth
from sklearn.metrics import mean_absolute_error
mean_absolute_error(y_test, y_preds)


2.136382352941176