In [1]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler

In [3]:
data = np.random.randint(0,1000,(10,2))
data

array([[ 22, 231],
       [125, 240],
       [543, 821],
       [814, 331],
       [ 32, 830],
       [755, 316],
       [894, 926],
       [446, 742],
       [522,  66],
       [831, 957]])

In [4]:
scaler_model = MinMaxScaler()

In [5]:
type(scaler_model)

sklearn.preprocessing._data.MinMaxScaler

In [6]:
scaler_model.fit(data) # Model to lear what the minimum and maximum value for each column

MinMaxScaler()

In [7]:
scaler_model.transform(data)

array([[0.        , 0.18518519],
       [0.11811927, 0.1952862 ],
       [0.59747706, 0.84736251],
       [0.90825688, 0.29741863],
       [0.01146789, 0.85746352],
       [0.84059633, 0.28058361],
       [1.        , 0.96520763],
       [0.48623853, 0.75869809],
       [0.5733945 , 0.        ],
       [0.92775229, 1.        ]])

In [8]:
scaler_model.fit_transform(data) # In one step

array([[0.        , 0.18518519],
       [0.11811927, 0.1952862 ],
       [0.59747706, 0.84736251],
       [0.90825688, 0.29741863],
       [0.01146789, 0.85746352],
       [0.84059633, 0.28058361],
       [1.        , 0.96520763],
       [0.48623853, 0.75869809],
       [0.5733945 , 0.        ],
       [0.92775229, 1.        ]])

In [9]:
import pandas as pd

# Let's simulate a supervised ML data

In [14]:
data = np.random.randint(0, 101, (50, 3))
df = pd.DataFrame(data=data, columns=['weight', 'height', 'age'])
df.head()

weight  height  age
0      22      46   45
1      81       3   33
2      66      18    8
3      35       1   83
4      96      54   90

In [15]:
X = df[['weight', 'height']]
y = df['age']

In [17]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [21]:
X_train.shape, X_test.shape

((33, 2), (17, 2))