In [1]:
import tensorflow as tf

INFO:tensorflow:Enabling eager execution
INFO:tensorflow:Enabling v2 tensorshape
INFO:tensorflow:Enabling resource variables
INFO:tensorflow:Enabling tensor equality
INFO:tensorflow:Enabling control flow v2


In [2]:

tf.print(tf.constant("hello") + tf.constant("world"))

helloworld


In [8]:
a = tf.constant(10)
b = tf.constant(20)
c = a + b
type(a)

tensorflow.python.framework.ops.EagerTensor

In [9]:
tf.print(a + b), print(c)

30
tf.Tensor(30, shape=(), dtype=int32)


(None, None)

In [10]:
fill_mat = tf.fill((4,5), 10)

In [11]:
my_zeros = tf.zeros((4,5))
my_ones = tf.ones((4,5))
myrandn = tf.random.normal((4,5), mean=0, stddev=1.0)
myrandu = tf.random.uniform((4,5), minval=0, maxval=1)

In [12]:
my_ops = [a, fill_mat, my_zeros, my_ones, myrandn, myrandu]
for o in my_ops:
    tf.print(o)
    print("\n")

10


[[10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]]


[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


[[-0.737118423 0.429291 1.60712123 0.441361964 -0.910629332]
 [-0.557100892 -0.877674401 -0.112463251 0.831537366 -0.151828721]
 [-0.793870568 0.399505407 -0.714152336 -0.531755626 0.0024629524]
 [-0.638634622 -0.561333597 0.966260135 -0.954557776 0.285447627]]


[[0.831645727 0.827078819 0.126921058 0.115712881 0.789498091]
 [0.0305063725 0.333105445 0.432439089 0.251762033 0.0420199633]
 [0.563636541 0.0300326347 0.278181434 0.214271784 0.882096648]
 [0.450122714 0.635629535 0.0335947275 0.671189547 0.528993249]]




In [13]:
a = tf.constant([ [1, 2],
                [3, 4] ])
a.shape

TensorShape([2, 2])

In [14]:
b = tf.constant([ [10], [100] ])
b.shape

TensorShape([2, 1])

In [15]:
result = tf.matmul(a, b)
tf.print(result)

[[210]
 [430]]


# TF Graphs

In [16]:
a = tf.constant(10)
b = tf.constant(20)
n = a + b
tf.print(n)

30


In [17]:
default_graph = tf.compat.v1.get_default_graph()

In [18]:
graph2 = tf.Graph()


In [19]:
with graph2.as_default():
    print(graph2 is tf.compat.v1.get_default_graph())

True


In [20]:
print(graph2 is tf.compat.v1.get_default_graph())

False


In [22]:
tensor = tf.random.uniform((4, 4), 0, 1)
tensor.shape

TensorShape([4, 4])

In [25]:
var_1 = tf.Variable(initial_value=tensor)
print(var_1)

<tf.Variable 'Variable:0' shape=(4, 4) dtype=float32, numpy=
array([[0.49332988, 0.3149389 , 0.75313795, 0.93582845],
       [0.82848775, 0.8663161 , 0.97890127, 0.536445  ],
       [0.93986404, 0.8856337 , 0.33595228, 0.4871974 ],
       [0.68694055, 0.7361766 , 0.04364061, 0.9582343 ]], dtype=float32)>


In [24]:
print(var_1)

<tf.Variable 'Variable:0' shape=(4, 4) dtype=float32, numpy=
array([[0.49332988, 0.3149389 , 0.75313795, 0.93582845],
       [0.82848775, 0.8663161 , 0.97890127, 0.536445  ],
       [0.93986404, 0.8856337 , 0.33595228, 0.4871974 ],
       [0.68694055, 0.7361766 , 0.04364061, 0.9582343 ]], dtype=float32)>
